<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'SensioLabs\Security\SecurityChecker' shared autowired service.

include_once $this->targetDirs[3].'/vendor/sensiolabs/security-checker/SensioLabs/Security/SecurityChecker.php';

return $this->services['SensioLabs\Security\SecurityChecker'] = new \SensioLabs\Security\SecurityChecker();
