<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG0msr5r\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG0msr5r/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerG0msr5r.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerG0msr5r\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerG0msr5r\srcDevDebugProjectContainer([
    'container.build_hash' => 'G0msr5r',
    'container.build_id' => 'dca9c893',
    'container.build_time' => 1554583538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG0msr5r');
