<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'SensioLabs\Security\Command\SecurityCheckerCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/sensiolabs/security-checker/SensioLabs/Security/Command/SecurityCheckerCommand.php';
include_once $this->targetDirs[3].'/vendor/sensiolabs/security-checker/SensioLabs/Security/SecurityChecker.php';

$this->services['SensioLabs\Security\Command\SecurityCheckerCommand'] = $instance = new \SensioLabs\Security\Command\SecurityCheckerCommand(${($_ = isset($this->services['SensioLabs\Security\SecurityChecker']) ? $this->services['SensioLabs\Security\SecurityChecker'] : ($this->services['SensioLabs\Security\SecurityChecker'] = new \SensioLabs\Security\SecurityChecker())) && false ?: '_'});

$instance->setName('security:check');

return $instance;
