<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.fxnbasy' shared service.

return $this->services['service_locator.fxnbasy'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['repository' => function () {
    $f = function (\App\Repository\TestRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Repository\TestRepository']) ? $this->services['App\Repository\TestRepository'] : ($this->services['App\Repository\TestRepository'] = new \App\Repository\TestRepository())) && false ?: '_'});
}]);
