<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\HelloWorldController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/HelloWorldController.php';

return $this->services['App\Controller\HelloWorldController'] = new \App\Controller\HelloWorldController();
