<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'services_resetter' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/DependencyInjection/ServicesResetter.php';

return $this->services['services_resetter'] = new \Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter(new RewindableGenerator(function () {
    if (isset($this->services['session'])) {
        yield 'session' => ${($_ = isset($this->services['session']) ? $this->services['session'] : null) && false ?: '_'};
    }
    if (isset($this->services['profiler'])) {
        yield 'profiler' => ${($_ = isset($this->services['profiler']) ? $this->services['profiler'] : null) && false ?: '_'};
    }
    if (isset($this->services['debug.stopwatch'])) {
        yield 'debug.stopwatch' => ${($_ = isset($this->services['debug.stopwatch']) ? $this->services['debug.stopwatch'] : null) && false ?: '_'};
    }
}, function () {
    return 0 + (int) (isset($this->services['session'])) + (int) (isset($this->services['profiler'])) + (int) (isset($this->services['debug.stopwatch']));
}), ['session' => 'save', 'profiler' => 'reset', 'debug.stopwatch' => 'reset']);
