<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\TestRepository' shared autowired service.

include_once $this->targetDirs[3].'/src/Repository/TestRepository.php';

return $this->services['App\Repository\TestRepository'] = new \App\Repository\TestRepository();
