<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEidtjn8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEidtjn8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEidtjn8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEidtjn8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEidtjn8\srcDevDebugProjectContainer([
    'container.build_hash' => 'Eidtjn8',
    'container.build_id' => '19006d7c',
    'container.build_time' => 1554633995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEidtjn8');
