<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxl13yq\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxl13yq/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVxl13yq.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVxl13yq\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVxl13yq\srcDevDebugProjectContainer([
    'container.build_hash' => 'Vxl13yq',
    'container.build_id' => '5497a126',
    'container.build_time' => 1554576575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxl13yq');
