<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container537ewzs\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container537ewzs/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container537ewzs.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container537ewzs\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container537ewzs\srcDevDebugProjectContainer([
    'container.build_hash' => '537ewzs',
    'container.build_id' => '36f9cc13',
    'container.build_time' => 1554571738,
], __DIR__.\DIRECTORY_SEPARATOR.'Container537ewzs');
